version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongo:27017/
      DATABASE_NAME: aischool
      OPENAI_API_KEY:
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:5173"
    environment:
      VITE_CHAT_SESSION_API_BASE_URL: http://localhost:8080

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
