//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: {fetch(url: RequestInfo, init?: RequestInit): Promise<Response>};
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: {fetch(url: RequestInfo, init?: RequestInit): Promise<Response>}) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * Chat
     * @return Successful Response
     */
    post(session_id: string, message: string): Promise<HandleChat> {
        let url_ = this.baseUrl + "/chat/{session_id}?";
        if(session_id === undefined || session_id === null)
            throw new Error("The parameter 'session_id' must be defined.");
        url_ = url_.replace("{session_id}", encodeURIComponent("" + session_id));
        if(message === undefined || message === null)
            throw new Error("The parameter 'message' must be defined and cannot be null.");
        else
            url_ += "message=" + encodeURIComponent("" + message) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPost(_response);
        });
    }

    protected processPost(response: Response): Promise<HandleChat> {
        const status = response.status;
        let _headers: any = {}; if(response.headers && response.headers.forEach) {response.headers.forEach((v: any, k: any) => _headers[k] = v);};
        if(status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = HandleChat.fromJS(resultData200);
                return result200;
            });
        } else if(status === 422) {
            return response.text().then((_responseText) => {
                let result422: any = null;
                let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result422 = HTTPValidationError.fromJS(resultData422);
                return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if(status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HandleChat>(null as any);
    }

    /**
     * List Sessions
     * @return Successful Response
     */
    get(session_id: string): Promise<ChatSession> {
        let url_ = this.baseUrl + "/chat/{session_id}";
        if(session_id === undefined || session_id === null)
            throw new Error("The parameter 'session_id' must be defined.");
        url_ = url_.replace("{session_id}", encodeURIComponent("" + session_id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<ChatSession> {
        const status = response.status;
        let _headers: any = {}; if(response.headers && response.headers.forEach) {response.headers.forEach((v: any, k: any) => _headers[k] = v);};
        if(status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = ChatSession.fromJS(resultData200);
                return result200;
            });
        } else if(status === 422) {
            return response.text().then((_responseText) => {
                let result422: any = null;
                let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result422 = HTTPValidationError.fromJS(resultData422);
                return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if(status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ChatSession>(null as any);
    }

    /**
     * Delete Session
     * @return Successful Response
     */
    delete(session_id: string): Promise<void> {
        let url_ = this.baseUrl + "/chat/{session_id}";
        if(session_id === undefined || session_id === null)
            throw new Error("The parameter 'session_id' must be defined.");
        url_ = url_.replace("{session_id}", encodeURIComponent("" + session_id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if(response.headers && response.headers.forEach) {response.headers.forEach((v: any, k: any) => _headers[k] = v);};
        if(status === 204) {
            return response.text().then((_responseText) => {
                return;
            });
        } else if(status === 422) {
            return response.text().then((_responseText) => {
                let result422: any = null;
                let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result422 = HTTPValidationError.fromJS(resultData422);
                return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if(status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class ChatClient {
    private http: {fetch(url: RequestInfo, init?: RequestInit): Promise<Response>};
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: {fetch(url: RequestInfo, init?: RequestInit): Promise<Response>}) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * Start New Session
     * @return Successful Response
     */
    post(message: string): Promise<CreateNewChat> {
        let url_ = this.baseUrl + "/chat?";
        if(message === undefined || message === null)
            throw new Error("The parameter 'message' must be defined and cannot be null.");
        else
            url_ += "message=" + encodeURIComponent("" + message) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPost(_response);
        });
    }

    protected processPost(response: Response): Promise<CreateNewChat> {
        const status = response.status;
        let _headers: any = {}; if(response.headers && response.headers.forEach) {response.headers.forEach((v: any, k: any) => _headers[k] = v);};
        if(status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = CreateNewChat.fromJS(resultData200);
                return result200;
            });
        } else if(status === 422) {
            return response.text().then((_responseText) => {
                let result422: any = null;
                let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result422 = HTTPValidationError.fromJS(resultData422);
                return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if(status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateNewChat>(null as any);
    }

    /**
     * List Sessions
     * @return Successful Response
     */
    get(): Promise<ChatSession[]> {
        let url_ = this.baseUrl + "/chat";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<ChatSession[]> {
        const status = response.status;
        let _headers: any = {}; if(response.headers && response.headers.forEach) {response.headers.forEach((v: any, k: any) => _headers[k] = v);};
        if(status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                if(Array.isArray(resultData200)) {
                    result200 = [] as any;
                    for(let item of resultData200)
                        result200!.push(ChatSession.fromJS(item));
                }
                else {
                    result200 = <any>null;
                }
                return result200;
            });
        } else if(status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ChatSession[]>(null as any);
    }
}

export class ChatMessage implements IChatMessage {
    role!: string;
    content!: string;

    [key: string]: any;

    constructor(data?: IChatMessage) {
        if(data) {
            for(var property in data) {
                if(data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if(_data) {
            for(var property in _data) {
                if(_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.role = _data["role"];
            this.content = _data["content"];
        }
    }

    static fromJS(data: any): ChatMessage {
        data = typeof data === 'object' ? data : {};
        let result = new ChatMessage();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for(var property in this) {
            if(this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["role"] = this.role;
        data["content"] = this.content;
        return data;
    }
}

export interface IChatMessage {
    role: string;
    content: string;

    [key: string]: any;
}

export class ChatSession implements IChatSession {
    /** MongoDB document ObjectID */
    _id?: string;
    session_title?: string;
    messages?: ChatMessage[];

    [key: string]: any;

    constructor(data?: IChatSession) {
        if(data) {
            for(var property in data) {
                if(data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if(!data) {
            this.session_title = "New Chat with AI";
        }
    }

    init(_data?: any) {
        if(_data) {
            for(var property in _data) {
                if(_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this._id = _data["_id"];
            this.session_title = _data["session_title"] !== undefined ? _data["session_title"] : "New Chat with AI";
            if(Array.isArray(_data["messages"])) {
                this.messages = [] as any;
                for(let item of _data["messages"])
                    this.messages!.push(ChatMessage.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ChatSession {
        data = typeof data === 'object' ? data : {};
        let result = new ChatSession();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for(var property in this) {
            if(this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["_id"] = this._id;
        data["session_title"] = this.session_title;
        if(Array.isArray(this.messages)) {
            data["messages"] = [];
            for(let item of this.messages)
                data["messages"].push(item.toJSON());
        }
        return data;
    }
}

export interface IChatSession {
    /** MongoDB document ObjectID */
    _id?: string;
    session_title?: string;
    messages?: ChatMessage[];

    [key: string]: any;
}

export class CreateNewChat implements ICreateNewChat {
    session_id!: string;
    session_title!: string;
    response!: string;

    [key: string]: any;

    constructor(data?: ICreateNewChat) {
        if(data) {
            for(var property in data) {
                if(data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if(_data) {
            for(var property in _data) {
                if(_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.session_id = _data["session_id"];
            this.session_title = _data["session_title"];
            this.response = _data["response"];
        }
    }

    static fromJS(data: any): CreateNewChat {
        data = typeof data === 'object' ? data : {};
        let result = new CreateNewChat();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for(var property in this) {
            if(this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["session_id"] = this.session_id;
        data["session_title"] = this.session_title;
        data["response"] = this.response;
        return data;
    }
}

export interface ICreateNewChat {
    session_id: string;
    session_title: string;
    response: string;

    [key: string]: any;
}

export class HTTPValidationError implements IHTTPValidationError {
    detail?: ValidationError[];

    [key: string]: any;

    constructor(data?: IHTTPValidationError) {
        if(data) {
            for(var property in data) {
                if(data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if(_data) {
            for(var property in _data) {
                if(_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if(Array.isArray(_data["detail"])) {
                this.detail = [] as any;
                for(let item of _data["detail"])
                    this.detail!.push(ValidationError.fromJS(item));
            }
        }
    }

    static fromJS(data: any): HTTPValidationError {
        data = typeof data === 'object' ? data : {};
        let result = new HTTPValidationError();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for(var property in this) {
            if(this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if(Array.isArray(this.detail)) {
            data["detail"] = [];
            for(let item of this.detail)
                data["detail"].push(item.toJSON());
        }
        return data;
    }
}

export interface IHTTPValidationError {
    detail?: ValidationError[];

    [key: string]: any;
}

export class HandleChat implements IHandleChat {
    session_id!: string;
    response!: string;

    [key: string]: any;

    constructor(data?: IHandleChat) {
        if(data) {
            for(var property in data) {
                if(data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if(_data) {
            for(var property in _data) {
                if(_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.session_id = _data["session_id"];
            this.response = _data["response"];
        }
    }

    static fromJS(data: any): HandleChat {
        data = typeof data === 'object' ? data : {};
        let result = new HandleChat();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for(var property in this) {
            if(this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["session_id"] = this.session_id;
        data["response"] = this.response;
        return data;
    }
}

export interface IHandleChat {
    session_id: string;
    response: string;

    [key: string]: any;
}

export class ValidationError implements IValidationError {
    loc!: Loc[];
    msg!: string;
    type!: string;

    [key: string]: any;

    constructor(data?: IValidationError) {
        if(data) {
            for(var property in data) {
                if(data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if(!data) {
            this.loc = [];
        }
    }

    init(_data?: any) {
        if(_data) {
            for(var property in _data) {
                if(_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if(Array.isArray(_data["loc"])) {
                this.loc = [] as any;
                for(let item of _data["loc"])
                    this.loc!.push(item);
            }
            this.msg = _data["msg"];
            this.type = _data["type"];
        }
    }

    static fromJS(data: any): ValidationError {
        data = typeof data === 'object' ? data : {};
        let result = new ValidationError();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for(var property in this) {
            if(this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if(Array.isArray(this.loc)) {
            data["loc"] = [];
            for(let item of this.loc)
                data["loc"].push(item);
        }
        data["msg"] = this.msg;
        data["type"] = this.type;
        return data;
    }
}

export interface IValidationError {
    loc: Loc[];
    msg: string;
    type: string;

    [key: string]: any;
}


export class Loc implements ILoc {

    [key: string]: any;

    constructor(data?: ILoc) {
        if(data) {
            for(var property in data) {
                if(data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if(_data) {
            for(var property in _data) {
                if(_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
        }
    }

    static fromJS(data: any): Loc {
        data = typeof data === 'object' ? data : {};
        let result = new Loc();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for(var property in this) {
            if(this.hasOwnProperty(property))
                data[property] = this[property];
        }
        return data;
    }
}

export interface ILoc {

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: {[key: string]: any;};
    result: any;

    constructor(message: string, status: number, response: string, headers: {[key: string]: any;}, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: {[key: string]: any;}, result?: any): any {
    if(result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}